/* automatically generated by ./repl_modules.sh lru
 * do not edit
 */
#include "squid.h"

extern REMOVALPOLICYCREATE createRemovalPolicy_lru;
void storeReplSetup(void)
{
	storeReplAdd("lru", createRemovalPolicy_lru);
}
