#include "squid.h"
const char *log_tags[] = 
{
	"NONE",
	"TCP_HIT",
	"TCP_MISS",
	"TCP_REFRESH_HIT",
	"TCP_REFRESH_FAIL_HIT",
	"TCP_REFRESH_MISS",
	"TCP_CLIENT_REFRESH_MISS",
	"TCP_IMS_HIT",
	"TCP_SWAPFAIL_MISS",
	"TCP_NEGATIVE_HIT",
	"TCP_MEM_HIT",
	"TCP_DENIED",
	"TCP_OFFLINE_HIT",
#if LOG_TCP_REDIRECTS
	"TCP_REDIRECT",
#endif
	"TCP_STALE_HIT",
	"TCP_ASYNC_HIT",
	"TCP_ASYNC_MISS",
	"UDP_HIT",
	"UDP_MISS",
	"UDP_DENIED",
	"UDP_INVALID",
	"UDP_MISS_NOFETCH",
	"ICP_QUERY",
	"TYPE_MAX"
};

const char *err_type_str[] = 
{
	"ERR_NONE",
	"ERR_READ_TIMEOUT",
	"ERR_LIFETIME_EXP",
	"ERR_READ_ERROR",
	"ERR_WRITE_ERROR",
	"ERR_SHUTTING_DOWN",
	"ERR_CONNECT_FAIL",
	"ERR_INVALID_REQ",
	"ERR_UNSUP_REQ",
	"ERR_INVALID_URL",
	"ERR_SOCKET_FAILURE",
	"ERR_DNS_FAIL",
	"ERR_CANNOT_FORWARD",
	"ERR_FORWARDING_DENIED",
	"ERR_NO_RELAY",
	"ERR_ZERO_SIZE_OBJECT",
	"ERR_FTP_DISABLED",
	"ERR_FTP_FAILURE",
	"ERR_URN_RESOLVE",
	"ERR_ACCESS_DENIED",
	"ERR_CACHE_ACCESS_DENIED",
	"ERR_CACHE_MGR_ACCESS_DENIED",
	"ERR_SQUID_SIGNATURE",
	"ERR_FTP_PUT_CREATED",
	"ERR_FTP_PUT_MODIFIED",
	"ERR_FTP_PUT_ERROR",
	"ERR_FTP_NOT_FOUND",
	"ERR_FTP_FORBIDDEN",
	"ERR_FTP_UNAVAILABLE",
	"ERR_ONLY_IF_CACHED_MISS",
	"ERR_TOO_BIG",
	"TCP_RESET",
	"ERR_INVALID_RESP",
	"ERR_MAX"
};

const char *lookup_t_str[] = 
{
	"LOOKUP_NONE",
	"LOOKUP_HIT",
	"LOOKUP_MISS"
};

const char *icp_opcode_str[] = 
{
	"ICP_INVALID",
	"ICP_QUERY",
	"ICP_HIT",
	"ICP_MISS",
	"ICP_ERR",
	"ICP_SEND",
	"ICP_SENDA",
	"ICP_DATABEG",
	"ICP_DATA",
	"ICP_DATAEND",
	"ICP_SECHO",
	"ICP_DECHO",
	"ICP_NOTIFY",
	"ICP_INVALIDATE",
	"ICP_DELETE",
	"ICP_UNUSED15",
	"ICP_UNUSED16",
	"ICP_UNUSED17",
	"ICP_UNUSED18",
	"ICP_UNUSED19",
	"ICP_UNUSED20",
	"ICP_MISS_NOFETCH",
	"ICP_DENIED",
	"ICP_HIT_OBJ",
	"ICP_END"
};

const char *swap_log_op_str[] = 
{
	"SWAP_LOG_NOP",
	"SWAP_LOG_ADD",
	"SWAP_LOG_DEL",
	"SWAP_LOG_VERSION",
	"SWAP_LOG_MAX"
};

